### ISSUE TITLE
Recompile with -fPIE

### ISSUE THREAD

**Issue by magadator** [SimVascular/svSolver#124]
I was trying to compile the code on Ubuntu 20.04.6 LTS with gcc and g++ version 9 (tried  with 7.5 as well).
The code fails to compile at 
[ 43%] Building CXX object FlowSolvers/ThreeDSolver/svPost/CMakeFiles/svpost.dir/post_solver.cxx.o
[ 44%] Linking CXX executable ../../../bin/svpost
/usr/bin/ld: /home/local/AD/magadator/SimVascular/solver/svSolver/Externals-build/sv_externals/bin/gnu/7.5/x64/vtk-8.1.1/lib/libvtkCommonCore-8.1.a(vtkDataArray.cxx.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE

I tried adding the "-fPIE" flag in almost all CFLAGS, CXXFLAGS, and EXE_LINKER_FLAGS but without any success. Is there any workaround to compile the code?

**Comment by ktbolt** [comment]
@magadator The error means that the VTK externals where not compiled with the -fPIE flag. But I do think the externals were compiled with that flag so maybe this is due to the differences in gcc versions.

The workaround is to use a local version of VTK when building svSolver.

**Comment by magadator** [comment]
It compiles with vtk 8.2
