### ISSUE TITLE
Installation problem of svSolver

### ISSUE THREAD

**Issue by MeriGJ** [SimVascular/svSolver#125]
Hi,
I have installed Simvascular and it is been some days that I am trying to install svSolver, every time it gives kind of error that I have to install it in a local drive, and C is a local drive right?! I have space in it so it is not a memory problem. I have already installed Intel Fortran Compiler Classic and I have Microsoft MPI. How can I solve the issue then? Any idea.
This is where it is trying to be installed:
C:\Program Files\SimVascular\svSolver\
 And I get: INstallation directory must be on a local drive.

**Comment by ktbolt** [comment]
@MeriGJ Please post this in the SV Forum so other users can see it.
