### ISSUE TITLE
./get-vtk-binaries.sh ubuntu_14 doesn't work

### ISSUE THREAD

**Issue by rya89** [SimVascular/svSolver#38]
Hello, 

I'm trying to compile svsolver on Ubuntu 16.04. So I figured that I have to do ./get-vtk-binaries.sh ubuntu_14. However, it seems that the link is broken and the real link is now (?) : http://simvascular.stanford.edu/downloads/public/svsolver/externals/linux/ubuntu/14.04/gnu/4.8/x64/RelWithDebInfo/2016.09.18/ubuntu.14.04.gnu.4.8.x64.RelWithDebInfo.2016.09.18.vtk.6.2.0.tar.gz 

Best regards, 

Ruiyi

**Comment by ktbolt** [comment]
@rya89 The preferred way to build **svsolver** is using CMake. Be sure to install MPI before trying to build

           sudo apt-get install libmpich-dev

**Comment by osmsc** [comment]
@rya89 -  You are correct, the links changed.  I've fixed the broken links so the make build should work again on Ubuntu.  Be sure to copy the global_overrides.mk and set the MPI option to match your system.

**Comment by osmsc** [comment]
Be sure to sync with the current master for svSolver.
