### ISSUE TITLE
svsolver-nompi produces NaNs.

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svSolver#45]
I am running a simple simulation (Cylinder Project Steady Case).  When I run the simulation using MPI the results look fine, tried 1, 2 and 4 processors.

When I run the simulation using **svsolver-nompi** the nonlinear residual starts increasing and eventually NaNs are produced. Here are some lines from **histor.dat**

```
     1 0.000E+00 4.190E-01  (   0)   9.733E+00   2.260E+28  <  5536- 1|  14> [   0 -   0]
     1 1.000E+00 3.784E-01  (   0)   5.144E-01   4.704E-01  <  5536- 1|  13> [   0 -   0]
     2 1.000E+00 2.488E+02  (  27)   2.377E+00   2.073E+00  <  1388- 1|  12> [   0 -   0]
     2 2.000E+00 3.353E-01  (   0)   3.163E-01   4.565E-03  <  1388- 1|  12> [   0 -   0]
     3 2.000E+00 3.880E+02  (  29)   2.405E-01   1.435E-02  <  1388- 1|  12> [   0 -   0]
     ...
    50 3.200E+01 1.492E+03  (  35)   1.404E-01   2.782E+00  <  1388- 1|  12> [   0 -   0]
    50 3.200E+01 2.667E+03  (  38)   1.258E-01   9.214E-01  <  1388- 1|  12> [   0 -   0]
    51 3.300E+01 2.041E+02  (  26)   1.215E-01   2.583E-03  <  1388- 1|  12> [   0 -   0]
    51 3.300E+01 1.835E+03  (  36)   8.940E-02   1.501E+01  <  1388- 1|  12> [   0 -   0]
    52 3.300E+01 2.177E+06  (  67)   4.974E+01   7.390E+02  <  1388- 1|  12> [   0 -   0]
    52 3.400E+01 2.900E+09  (  98)   1.829E+03   1.356E+03  <  1388- 1|  12> [   0 -   0]
    53 3.400E+01 4.006E+12  ( 129)   1.652E+00   1.766E+01  <  1388- 1|  12> [   0 -   0]
    53 3.500E+01 5.150E+15  ( 160)   6.142E+03   3.594E+03  <  1388- 1|  12> [   0 -   0]
    54 3.500E+01 6.314E+19  ( 201)   3.206E+00   1.496E+03  <  3576- 1|  13> [   0 -   0]
    54 3.500E+01 9.149E+21  ( 223)   1.777E+01   1.407E+03  <  1388- 1|  12> [   0 -   0]

```
 
Ive tried this on Ubunto and MacOS using the latest svSolver release.

**Comment by ktbolt** [comment]
@wgyang Could you please have a look at this? The dummy MPI library should be working OK but I can't figure out where the solver iterations are happening.

**Comment by wgyang** [comment]
Most subroutines in dummy MPI do nothing such as mpi_bcast and mpi_isend. There are several solver subroutines calling MPI commands e.g. commu. These commands are not executed correctly with dummy MPI library, therefore, the residual can't be right.

**Comment by wgyang** [comment]
FYI,
Time marching and nonlinear iterations are performed in subroutine itrdrv (see itdrv-closedloop-varwall-coronary.f) 
For each time step,  subroutine itrPredictr predicts the solution and subroutine SolFlow solves the linear system to get a correction.

**Comment by ktbolt** [comment]
@wgyang I'll take it from here, do some tests. Thanks!

**Comment by ktbolt** [comment]
There are a lot of checks in the code for **numpe > 1**, where **numpe** is the number of processors. The function **commu** is only called if **numpe > 1**.

**Comment by ktbolt** [comment]
@wgyang The dummy MPI functions are correctly reproducing MPI functionality, the problem is that the MPI constants defined in the **dummyMPI/mpi.h** file that it uses (e.g. MPI_DOUBLE) don't match those define in the /usr/include/mpi.h which the solver code uses.

**Comment by wgyang** [comment]
Thank you for letting me know the cause!

**Comment by osmsc** [comment]
@ktbolt - this is definitely an issue.  I wonder if it's just in the cmake build.  If you are building with the dummy mpi you obviously need to pick up the right mpi.h header.  This is true for openmpi and mpich, you need to compile with the same mpi.h header you are linking against.

**Comment by ktbolt** [comment]
@osmsc Correct! The CMake code was setting the MPI include directory to the MPICH directory for both mpi and no-mpi builds. After six hours of digging into the CMake code and fooling around with include directories I got it to work.

I compared the no-mpi and mpi for 1 processor and 4 processors, all results match.

Note that the solver code in most places checks for **numpe = 1** and branches around the MPI calls. However, there are a few solver functions that don't follow this strategy and that is where the problem occurred. Developers need to follow a single strategy when developing code and adopt whatever strategy is already in place.

I also added my own **numpe = 1** branches around the MPI calls (these were all MPI_ALLREDUCE calls) and that worked too. But I won't check that in since it required me to modify several functions and I would not be able to properly test.

**Comment by ktbolt** [comment]
I merged into master and tried to compile on Ubuntu 16 but it failed: can't find mpi.h. I reverted the merge and will get back to this later.

**Comment by ktbolt** [comment]
I'm getting back to this because several users have tried to use no-mpi and the solver does not converge causing confusion.

**Comment by ktbolt** [comment]
I've fixed this so `svsolver-nompi` now builds with OpenMPI and MPICH. 

The `svsolver-nompi` results also match MPI results.
