### ISSUE TITLE
svSolver trouble compiling - Issue linking VTK?

### ISSUE THREAD

**Issue by melodydong** [SimVascular/svSolver#47]
I tried compiling svSolver on Ubuntu 18 and it failed due to issues linking vtk for svpost.  Consequently, nothing is created in the bin folder (no svpre, svsolver, etc.).

I get the following page of errors similar to the one below:
/home/melody/build/Externals-build/sv_externals/bin/gnu/5.5/x64/vtk-6.2.0/lib/libvtkCommonExecutionModel-6.2.a(vtkPolyDataAlgorithm.cxx.o): relocation R_X86_64_32S against symbol `_ZTV20vtkPolyDataAlgorithm' can not be used when making a PIE object; recompile with -fPIC

**Comment by ktbolt** [comment]
@melodydong The Ubuntu 18 g++-5 (5.5), g++-6, g++-7 compilers are all configured with PIE (position-independent executables) by default. The VTK externals are static libraries and you can't make a executable position independent using a static libraries.

You will need to add a **-no-pie** flag to the **CMAKE_CXX_FLAGS** variable using ccmake (press t when in ccmake to show advanced options). I tested on Ubuntu 18 and it compiled OK with this flag.

**Comment by melodydong** [comment]
Successfully compiled and ran on my Linux Ubuntu 18 machine and the WSL on my Windows laptop. Thanks for the fix!
