### ISSUE TITLE
QHistRCR.dat and PHistRCR.dat corrupted after job is canceled

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svSolver#80]
I have simulations with many (>100) restarts. It happens frequently that restarts crash in solver_subroutines.f because the files QHistRCR.dat and PHistRCR.dat can't be read. They're either empty or the rows are partially filled. 

Currently, these files are re-written for every time step. This can cause the file to be corrupted if the job is canceled while writing to disk. In that case, the whole simulation data is lost and can't be restarted.

@ktbolt suggested writing these files for every time step. That way, in case writing to disk is not completed, one can always revert to the last saved time step.

**Comment by mrp089** [comment]
I'm still experiencing the same problem. It looks like `numstart.dat` is written **before** `QHistRCR.dat` and `PHistRCR.dat`. See this example:
```
-rw-r--r-- 1 pfaller amarsden 5.6M Aug  5 02:24 QHistRCR.dat.13237
-rw-r--r-- 1 pfaller amarsden 5.6M Aug  5 02:24 QHistRCR.dat.13238
-rw-r--r-- 1 pfaller amarsden 4.4M Aug  5 02:24 QHistRCR.dat.13239
-rw-r--r-- 1 pfaller amarsden 5.6M Aug  5 02:24 PHistRCR.dat.13237
-rw-r--r-- 1 pfaller amarsden 5.6M Aug  5 02:24 PHistRCR.dat.13238
ls: cannot access PHistRCR.dat.13239: No such file or directory
```
It appears that the job was terminated while `QHistRCR.dat.13239` was written and before writing to `PHistRCR.dat.13239` started. However, `numstart.dat` had already been incremented to `13239`. Restarting failed since `QHistRCR.dat.13239` and `PHistRCR.dat.13239` can't be read.

**Comment by ktbolt** [comment]
I looked in the code again and I see that the **numstart.dat** IS indeed written before **QHistRCR.dat** and **PHistRCR.dat**; thought it was the last file written. Sorry!

You might could try moving the code in **itrdrv-closedloop-varwall-coronary.f**
```
c 
c ... update the flow history for the RCR convolution
c    
            if(numRCRSrfs.gt.zero) then
               call UpdHistConv(y,nsrflistRCR,numRCRSrfs) !uses lstep
               call UpdRCR(y,nsrflistRCR,numRCRSrfs)
            endif
```

before 

```
c
c ... write out the solution
c
            if (mod(lstep, ntout) .eq. 0) then
                 call restar ('out ',  yold  ,ac)
               if(ideformwall.eq.1)
     &            call write_displ(myrank, lstep, nshg, 3, uold,
     &                              deformflag)
            endif
```

I'm not sure of the dependencies though.

**Comment by mrp089** [comment]
Thanks @ktbolt! It looks like the output function `restar` also does some computations: https://github.com/SimVascular/svSolver/blob/master/Code/FlowSolvers/ThreeDSolver/svSolver/solver_subroutines.f#L13828

Would it make sense to create a separate function that **only** writes a new `numstart.dat` after everything else has been done? Then I could leave the rest of the update/output functions (`UpdHistConv, UpdRCR, UpdHistPlvConv, Updcalc, UpdateLagrangeCoef, newBflux, Bflux`) _as is_.

**Comment by ktbolt** [comment]
I was thinking the same thing, just write out numstart.dat as the last file. The **restar()** subroutine is called from within the time stepping loop and once after it, need to write numstart.dat  in both places maybe.
